#!/usr/bin/env sh

if [ ${#} -eq 2 ]; then
  echo "You need to provide a path" 2>&1
  exit 1
fi

path="${1}"
sess=$(basename "${path}")

if [ -n "$(tmux list-sessions | grep "^${sess}:")" ] ; then
  if [ $TMUX ]; then
    tmux switch-client -t "${sess}"
  else
    tmux attach-session -d -t "${sess}"
  fi
else
  if [ $TMUX ]; then
      ( tmux new-session -d -s "${sess}" ) && \
      ( tmux switch-client -t "${sess}" ) && \
      ( tmux send-keys -t "${sess}:0.0" "cd ${path}" Enter "clear" Enter )
  else
    ( cd "${path}" && DISPLAY= tmux new-session -s "${sess}" )
  fi
fi


